### ISSUE TITLE
Shelly Firmware 

### ISSUE THREAD

**Issue by lechez01** [funkmaster86/dbus-shelly-pro-3em-smartmeter#7]
What Shelly pro 3em firmware is the software for? There is a new firmware for the pro 3em 1.1.0 from 2023-12-19.
I have the 0.14.1 it works, but I have sometimes the problem that the pro 3em isn´t reachable. 

Rgds
André

**Comment by leowinterde** [comment]
I am running the current firmware 1.2.2 - so far no problems

**Comment by john-trn** [comment]
I have firmware 1.3.2 and VenusOS cannot connect to Pro 3em

**Comment by peregrines2** [comment]
For me it is working with newest Shelly firmware (1.3.3).
1.3.2 also worked without problems.

**Comment by lechez01** [comment]
Now it is working for me fine with 1.4.4, too. 
Thank you for your answers.
